# Generated by Django 4.1.1 on 2024-12-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='assignee',
            new_name='team_lead',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='assignment',
            new_name='team_members',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='name',
            new_name='title',
        ),
    ]
