# Generated by Django 4.1.1 on 2024-12-10 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_employee_is_team_lead_employee_team_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_rename_assignee_projects_team_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='added_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('canceled', 'Canceled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='team_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projects',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='Assignment', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='tech_stack',
            field=models.TextField(blank=True, null=True),
        ),
    ]
