# Generated by Django 4.1.1 on 2024-12-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_employee_is_team_lead_employee_team_lead'),
        ('projects', '0003_alter_projects_added_by_alter_projects_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='account_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_manager', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='team_member', to='employees.employee'),
        ),
    ]
