# Generated by Django 4.1.1 on 2024-12-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projects_account_manager_alter_projects_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='account_manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
