# Generated by Django 4.1.1 on 2024-12-10 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_employee_is_team_lead_employee_team_lead'),
        ('projects', '0005_alter_projects_account_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='team_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_lead_employee', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='team_member_employee', to='employees.employee'),
        ),
    ]
