# Generated by Django 4.1.1 on 2022-09-28 10:46

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.CharField(default=uuid.UUID('26f1789b-ca7a-4aed-912f-54639757f347'), max_length=50, primary_key=True, serialize=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('department_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.CharField(default=uuid.UUID('26f1789b-ca7a-4aed-912f-54639757f347'), max_length=50, primary_key=True, serialize=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.TextField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('national_id_number', models.IntegerField(unique=True)),
                ('emergency_contact_number', models.TextField(max_length=20)),
                ('gender', models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE'), ('OTHER', 'OTHER')], max_length=255)),
                ('designation', models.CharField(max_length=50)),
                ('bank', models.CharField(max_length=50)),
                ('account_number', models.TextField(max_length=50)),
                ('profile_pic', models.URLField()),
                ('joining_date', models.DateTimeField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.department')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
