# Generated by Django 4.1.1 on 2022-09-27 19:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default=uuid.UUID('ecaddf7c-44b9-4c4e-bed6-53028cece0c6'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default=uuid.UUID('ecaddf7c-44b9-4c4e-bed6-53028cece0c6'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
