# Generated by Django 4.1.1 on 2023-02-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.CharField(max_length=50),
        ),
    ]
