# Generated by Django 4.1.1 on 2023-02-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='images', verbose_name='profile img'),
        ),
    ]
