# Generated by Django 4.1.1 on 2023-06-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='remaining_leaves',
            field=models.IntegerField(default=20, null=True),
        ),
    ]
