# Generated by Django 4.1.1 on 2024-01-18 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0010_employee_extra_leaves_employee_total_leaves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='team_lead',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_team_lead': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_lead_employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
