# Generated by Django 4.1.1 on 2024-03-18 10:14

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_extra_leaves_employee_total_leaves_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('subject', models.CharField(max_length=255)),
                ('remarks', models.TextField(max_length=20)),
                ('increment', models.FloatField(default=0)),
                ('interval_from', models.DateField()),
                ('interval_to', models.DateField()),
                ('review_date', models.DateField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_by', to='employees.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employees.employee')),
                ('review_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_by', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_history',
            },
        ),
    ]
