# Generated by Django 4.1.1 on 2024-03-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employeehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeehistory',
            name='added_date',
            field=models.DateTimeField(),
        ),
    ]
