# Generated by Django 4.1.1 on 2024-03-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employeehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeehistory',
            name='increment',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='remarks',
            field=models.TextField(max_length=20),
        ),
    ]
