# Generated by Django 4.1.1 on 2024-08-05 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0012_alter_employeehistory_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='team_lead',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_team_lead': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_lead_employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
