# Generated by Django 4.1.1 on 2024-08-16 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_employeehistory_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_team_lead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='team_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='associates', to='employees.employee'),
        ),
    ]
