# Generated by Django 4.1.1 on 2025-04-28 15:51

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_employee_is_team_lead_employee_team_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenure',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('INTERNSHIP', 'INTERNSHIP'), ('PROBATION', 'PROBATION'), ('CONFIRMED', 'CONFIRMED')], default='PROBATION', max_length=20)),
                ('interval_from', models.DateField()),
                ('interval_to', models.DateField()),
                ('allocated_leaves', models.IntegerField(default=0)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenure_added_by', to='employees.employee')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenure', to='employees.employee')),
            ],
            options={
                'db_table': 'tenure',
            },
        ),
    ]
