# Generated by Django 4.1.1 on 2025-05-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_alter_employeehistory_added_by_employeetenure'),
        ('employees', '0013_employee_is_team_lead_employee_team_lead'),
    ]

    operations = [
    ]
