# Generated by Django 4.1.1 on 2025-04-30 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_tenure'),
        ('employees', '0014_tenure_alter_employeehistory_added_by_and_more'),
    ]

    operations = [
    ]
