# Generated by Django 4.1.1 on 2025-05-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_tenure_alter_employeehistory_added_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeehistory',
            name='remarks',
            field=models.TextField(),
        ),
    ]
