# Generated by Django 4.1.1 on 2023-11-28 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_tenant'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policies',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_polices', to='user.tenant'),
            preserve_default=False,
        ),
    ]
