# Generated by Django 4.1.1 on 2022-09-28 12:54

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('basic_salary', models.FloatField()),
                ('bonus', models.FloatField()),
                ('reimbursement', models.FloatField()),
                ('travel_allowance', models.FloatField()),
                ('tax_deduction', models.FloatField()),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=50)),
                ('released', models.BooleanField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
