# Generated by Django 4.1.1 on 2023-06-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_payroll_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='reimbursement',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='released',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='tax_deduction',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='travel_allowance',
            field=models.FloatField(default=0),
        ),
    ]
