# Generated by Django 4.1.1 on 2022-09-28 10:46

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('id', models.CharField(default=uuid.UUID('26f1789b-ca7a-4aed-912f-54639757f347'), max_length=50, primary_key=True, serialize=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('asset_model', models.CharField(max_length=50)),
                ('asset_type', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssignedAsset',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.CharField(default=uuid.UUID('26f1789b-ca7a-4aed-912f-54639757f347'), max_length=50, primary_key=True, serialize=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='assets.asset')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
