# Generated by Django 4.1.1 on 2023-02-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_image',
            field=models.FileField(default='null', upload_to='asset', verbose_name='asset img'),
        ),
    ]
