# Generated by Django 4.1.1 on 2024-01-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_image',
            field=models.FileField(blank=True, null=True, upload_to='asset', verbose_name='asset img'),
        ),
    ]
