# Generated by Django 4.1.1 on 2022-09-26 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.TextField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('resume', models.FileField(upload_to='')),
                ('status', models.CharField(choices=[('IN_PROCESS', 'IN_PROCESS'), ('SCHEDULED', 'SCHEDULED'), ('PENDING', 'PENDING'), ('SELECTED', 'SELECTED'), ('REJECTED', 'REJECTED')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Referrals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitments.recruits')),
                ('referer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'unique_together': {('recruit', 'referer')},
            },
        ),
    ]
