# Generated by Django 4.1.1 on 2022-10-03 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('recruitments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrals',
            name='referer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruits_referred', to='employees.employee'),
        ),
        migrations.AlterUniqueTogether(
            name='referrals',
            unique_together={('recruit', 'referer')},
        ),
    ]
