# Generated by Django 4.1.1 on 2023-02-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruits',
            name='resume',
            field=models.CharField(max_length=200),
        ),
    ]
