# Generated by Django 4.1.1 on 2023-02-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0004_alter_recruits_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruits',
            name='resume',
            field=models.FileField(upload_to='media', verbose_name='resume'),
        ),
    ]
