# Generated by Django 4.1.1 on 2024-02-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0006_alter_recruits_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruits',
            name='position',
            field=models.CharField(max_length=30),
        ),
    ]
