# Generated by Django 4.1.1 on 2024-03-19 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_extra_leaves_employee_total_leaves_and_more'),
        ('recruitments', '0007_alter_recruits_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrals',
            name='referer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruits_referred', to='employees.employee'),
        ),
    ]
