# Generated by Django 4.1.1 on 2024-03-20 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_extra_leaves_employee_total_leaves_and_more'),
        ('recruitments', '0008_recruitshistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitshistory',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruit_history_added_by', to='employees.employee'),
        ),
    ]
