# Generated by Django 4.1.1 on 2024-06-27 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employeehistory'),
        ('recruitments', '0009_recruitshistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruits',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
        migrations.AddField(
            model_name='recruits',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
