# Generated by Django 4.1.1 on 2024-10-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitments", "0010_recruits_assigned_to_recruits_interview_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitshistory",
            name="remarks",
            field=models.TextField(max_length=500),
        ),
    ]
