# Generated by Django 4.1.1 on 2025-04-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0011_alter_recruitshistory_remarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruits',
            options={'ordering': ['-created']},
        ),
    ]
