# Generated by Django 4.1.1 on 2022-09-26 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('basic_salary', models.IntegerField()),
                ('bonus', models.IntegerField()),
                ('reimbursement', models.IntegerField()),
                ('travel_allowance', models.IntegerField()),
                ('tax_deduction', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=50)),
                ('released', models.BooleanField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
