# Generated by Django 4.1.1 on 2023-02-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('APPROVED', 'APPROVED')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='from_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='leave_type',
            field=models.CharField(choices=[('SICK_LEAVE', 'SICK_LEAVE'), ('CASUAL_LEAVE', 'CASUAL_LEAVE'), ('MATERNITY_LEAVE', 'MATERNITY_LEAVE'), ('PATERNITY_LEAVE', 'PATERNITY_LEAVE'), ('MARRIAGE_LEAVE', 'MARRIAGE_LEAVE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='to_date',
            field=models.CharField(max_length=50),
        ),
    ]
