# Generated by Django 4.1.1 on 2023-02-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_leaves_status_alter_leaves_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='from_date',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='to_date',
            field=models.DateField(max_length=50),
        ),
    ]
