# Generated by Django 4.1.1 on 2023-02-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_leaves_from_date_alter_leaves_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='to_date',
            field=models.DateField(),
        ),
    ]
