# Generated by Django 4.1.1 on 2023-06-14 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_remaining_leaves'),
        ('attendance', '0006_leaves_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to='employees.employee'),
        ),
    ]
