# Generated by Django 4.1.1 on 2024-01-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_leaves_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='leave_type',
            field=models.CharField(choices=[('SICK_LEAVE', 'SICK_LEAVE'), ('CASUAL_LEAVE', 'CASUAL_LEAVE'), ('MATERNITY_LEAVE', 'MATERNITY_LEAVE'), ('PATERNITY_LEAVE', 'PATERNITY_LEAVE'), ('MARRIAGE_LEAVE', 'MARRIAGE_LEAVE'), ('EMERGENCY_LEAVE', 'EMERGENCY_LEAVE')], max_length=50),
        ),
    ]
