# Generated by Django 4.1.1 on 2025-05-14 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_tenure_alter_employeehistory_added_by_and_more'),
        ('attendance', '0010_alter_leaves_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('LATE_ARRIVAL', 'LATE_ARRIVAL'), ('EARLY_ARRIVAL', 'EARLY_ARRIVAL'), ('EARLY_DEPARTURE', 'EARLY_DEPARTURE'), ('LATE_DEPARTURE', 'LATE_DEPARTURE'), ('ON_TIME', 'ON_TIME'), ('ATTENDANCE_REQUEST', 'ATTENDANCE_REQUEST')], max_length=50),
        ),
        migrations.CreateModel(
            name='AttendanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out'), ('CHECK_IN_CHECK_OUT', 'Check In and Check Out')], max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('attendance_date', models.DateField()),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reason', models.TextField(max_length=500)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_approver', to='employees.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_requests', to='employees.employee')),
            ],
            options={
                'db_table': 'attendance_requests',
            },
        ),
    ]
