name: HRMS CI

on:
  push:
    branches: [ "staging", "main" ]
  pull_request:
    branches: [ "staging", "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      env:
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      run: python manage.py migrate
    - name: Run tox
      env:
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      run: tox
    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      run: pytest

  # deploy:
  #   needs: build-test
  #   name: Deploy to server
  #   runs-on: ubuntu-latest
  #   if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.base_ref == 'staging')
  #   steps:
  #     - name: executing remote ssh commands using ssh key
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.SERVER_HOST }}
  #         username: ${{ secrets.SERVER_USERNAME }}
  #         key: ${{ secrets.SERVER_KEY }}
  #         port: ${{ secrets.SERVER_PORT }}
  #         script: |
  #           /home/ubuntu/server/deploy/deploy_dev.sh
  
  deploy:
    needs: build-test
    name: Deploy to server
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.base_ref == 'staging')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setting up SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SERVER_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-65-0-132-23.ap-south-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: SSH and Deploy
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@ec2-65-0-132-23.ap-south-1.compute.amazonaws.com << 'ENDSSH'
          cd hrms-dev
          git pull
          docker-compose up -d
          ENDSSH
